#!/usr/bin/env bash
configdir=${PWD}
cd ~
if [ -L .vim ];
then
  rm .vim
fi

if [ -L .vimrc ];
then
  rm .vimrc
fi

if [ -e .vim ];
then
  mkdir .old > /dev/null
  mv .vim .old
fi

if [ -e .vimrc ];
then
  mkdir .old > /dev/null
  mv .vimrc .old
fi

ln -s ${configdir}/vim .vim
ln -s ${configdir}/vimrc .vimrc

